"""
透传桩：仅用于「非内置、且 LLM 代码生成失败或未配置 Key」的算子。
内置算子请使用 `builtin_delegate_codegen`；自定义算子优先 `llm_operator_codegen`。
"""

from __future__ import annotations

import json
from typing import Any


def _one_line_desc(step: dict[str, Any]) -> str:
    d = str(step.get("description") or "").strip().replace("\n", " ").replace('"""', "'")
    return d[:400] if d else "No description."


def generate_stub_module(
    *,
    step_index: int,
    step: dict[str, Any],
    registry_spec: dict[str, Any] | None,
) -> str:
    op = str(step.get("operator") or "unknown")
    sid = str(step.get("step_id") or f"step_{step_index}")
    ik = step.get("input_keys") if isinstance(step.get("input_keys"), list) else []
    ok = step.get("output_keys") if isinstance(step.get("output_keys"), list) else []
    params = step.get("parameters") if isinstance(step.get("parameters"), dict) else {}
    req_llm = bool(registry_spec.get("requires_llm")) if isinstance(registry_spec, dict) else False
    reg_desc = ""
    if isinstance(registry_spec, dict):
        reg_desc = str(registry_spec.get("description") or "").strip().replace("\n", " ")[:300]

    desc = _one_line_desc(step)
    params_py = repr(params)
    ik_py = repr(ik)
    ok_py = repr(ok)

    llm_note = "\n    # LLM_CALL: 执行期注入 core.llm_client 或等价服务\n" if req_llm else ""

    if op == "read_data":
        body = f'''    """{desc}

    注册表说明: {reg_desc or "n/a"}
    桩行为: 不读盘，返回传入的 records 或空列表；真实执行器应读取 PARAMETERS['file_path']。"""
    _ = context{llm_note}
    return list(records) if records is not None else []'''

    elif op == "write_data":
        body = f'''    """{desc}

    注册表说明: {reg_desc or "n/a"}
    桩行为: 不写盘，透传 records；真实执行器应写入 PARAMETERS['file_path']。"""
    _ = context{llm_note}
    return list(records) if records is not None else []'''

    else:
        body = f'''    """{desc}

    注册表说明: {reg_desc or "n/a"}
    桩行为: 透传 records，占位以便串起数据流。"""
    _ = context{llm_note}
    return list(records) if records is not None else []'''

    header = f'''# -*- coding: utf-8 -*-
# Generated by DataEvolver (passthrough stub). Re-run instantiate after configuring API key for LLM codegen, or replace operator in orchestration.
from __future__ import annotations

from typing import Any

OPERATOR_NAME = {json.dumps(op)}
STEP_INDEX = {step_index}
STEP_ID = {json.dumps(sid)}
INPUT_KEYS = {ik_py}
OUTPUT_KEYS = {ok_py}
PARAMETERS = {params_py}
REQUIRES_LLM = {req_llm}


def run(records: list[dict[str, Any]] | None = None, context: dict[str, Any] | None = None) -> list[dict[str, Any]]:
'''

    footer = "\n\n\ndef describe() -> str:\n    return OPERATOR_NAME + \": \" + " + json.dumps(desc[:200]) + "\n"

    # 可选：与旧版「python stub.py in out」习惯对齐；推荐仍通过 subprocess_bridge 调用。
    stub_cli = """

if __name__ == "__main__":
    import argparse
    import json
    import sys
    from pathlib import Path

    ap = argparse.ArgumentParser(description="DataEvolver operator_stub CLI: JSONL in → run() → JSONL out.")
    ap.add_argument("input_jsonl")
    ap.add_argument("output_jsonl")
    ap.add_argument("repo_root", nargs="?", default=".")
    args = ap.parse_args()
    root = Path(args.repo_root).resolve()
    rows: list[dict[str, Any]] = []
    with open(args.input_jsonl, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            obj = json.loads(line)
            if isinstance(obj, dict):
                rows.append(obj)
    ctx: dict[str, Any] = {"root": str(root), "pipeline_id": "", "llm_config": {}, "on_usage": None}
    out = run(rows, ctx) or []
    with open(args.output_jsonl, "w", encoding="utf-8") as wf:
        for r in out:
            if isinstance(r, dict):
                wf.write(json.dumps(r, ensure_ascii=False) + '\n')
    sys.exit(0)
"""

    return header + body + footer + stub_cli
